package {{$name}};

# ABSTRACT: blah blah blah

use strict;
use warnings;

# VERSION: generated by dzil

sub new { bless {}, shift }

1;

__END__

=head1 SYNOPSIS

  use {{$name}}
  my $obj = {{$name}}->new;

=method new

Returns blessed hashref.

=cut
